#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, sys, struct, zlib

# ----- RECEIVER CLASS -----
class Receiver:
    def __init__(self):
        '''
        Constructor for the Receiver class.
        '''
        # create UDP socket, bind to any available IP & port
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.port = self.socket.getsockname()[1]
        self.log("Bound to port %d" % self.port)

        self.remote_host = None
        self.remote_port = None

        # ----- RECEIVER VARIABLES -----
        # save acknowledged packets so we know what has finished being handled
        self.sequences_acknowledged = []
        # seq num counter to figure out next packet to print to stdout
        # assuming packets start at number 0 when sender sends it
        self.expected_seq_num = 0
        # store all ack messages in case packets are out of order, and need to print at the very end
        self.ack_messages = {}
        

    def send(self, message):
        '''
        Sends a message to the remote host.

        Args:
            message (dict): The message to send.
        '''
        self.socket.sendto(json.dumps(message).encode('utf-8'), (self.remote_host, self.remote_port))


    def log(self, message):
        '''
        Logs a message to stderr.

        Args:
            message (str): The message to log.
        '''
        sys.stderr.write(message + "\n")
        sys.stderr.flush()


    def sort_ack_messages(self):
        '''
        Sorts the acknolwedgment messages by sequence number, and orders the packets
        in the correct order. Serves as a cache to store all packets until they
        can be printed in the correct order.
        '''
        sorted_ack_messages = {}
        # sort the ack messages dict by sequence number, to order the packets; key = sequence number
        sorted_keys = sorted(self.ack_messages.keys())
        # iterate thru sorted seq nums, & store the entire message to print later
        for key in sorted_keys:
            sorted_ack_messages[key] = self.ack_messages[key]
        self.ack_messages = sorted_ack_messages


    def print_ordered_packets(self):
        '''
        Iterates through the sorted acknowledgment messages, and prints the
        packets in the correct order. By using the variable expected_seq_num, we
        can print the packets in the correct order starting from 0 and
        incrementing as we receive more packets. Printed/delivered packets are
        stored in the sequences_acknowledged list to later delete.
        '''
        # iterate through each entry in the ack_messages dict,
        # starting from expected seq num of 0, we will print it, and increment for the next expected seq num (0, 1, ..., etc)
        # so the packets are printed in correct order
        for key, value in self.ack_messages.items():
            if key == self.expected_seq_num:
                print(value["data"], end='', flush=True)
                self.expected_seq_num += 1
                # we've printed the packet, so it has been acknowledged & delivered
                self.sequences_acknowledged.append(key)
                

    def run(self):
        '''
        Main loop for the receiver. This function listens for incoming packets,
        and sends acknowledgements for each packet received. It prints the
        packets in the correct order & drops corrupted packets with an incorrect
        checksum.
        '''
        while True:
            socks = select.select([self.socket], [], [])[0]
            for conn in socks:
                packet, addr = conn.recvfrom(65535)

                if self.remote_host is None:
                    self.remote_host = addr[0]
                    self.remote_port = addr[1]

                # if no data, skip
                if not packet:
                    continue
                
                # # attempt to decode the data, if it fails, skip
                # try:
                #     msg = json.loads(packet.decode('utf-8'))
                    
                #     # check if 'data' key is in the message, if not, skip
                #     if 'data' not in msg.keys():
                #         continue

                #     # decoding of struct packed seq, time, & checksum
                #     packed_data = msg['pckd']
                #     packet = base64.b64decode(packed_data)
                #     msg['seq'], msg['time'], msg['chs'] = struct.unpack('IdB', packet)
                    
                #     #decode of main compressed data, & decompress it into msg['data']
                #     compressed_data = base64.b64decode(msg['data'])
                #     decompressed_data = zlib.decompress(compressed_data).decode('utf-8')
                #     msg['data'] = decompressed_data
                
                # except json.JSONDecodeError as e:
                #     self.log(f"**json decoder error**; {e}")
                #     continue
                # except zlib.error as e:
                #     self.log(f"**zlib error**; {e}")
                #     continue

                header_format = 'IIdB'
                header_size = struct.calcsize(header_format)
                
                # Unpack the header
                header = packet[:header_size]
                sequence_number, data_size, current_time, checksum = struct.unpack(header_format, header)
                
                # Extract the data using the size specified in the header
                compressed_data = packet[header_size:header_size+data_size]

                # calculate checksum of received packet to compare with expected checksum
                received_checksum = sum(bytearray(compressed_data)) % 256

                # verify checksum of received packet
                if received_checksum == checksum:
                    # log received data message for verified packet
                    self.log(f"**Received ack**; {sequence_number}")
                    data = zlib.decompress(compressed_data).decode('utf-8')

                    # if the packet seq num isnt in already in the ack_messages we've saved, then store the entire message
                    # we will hang on to thess messages until we can print it to stdout in the correct order
                    if sequence_number not in self.ack_messages.keys():
                        # store the entire message to print at the end
                        self.ack_messages[sequence_number] = {
                            "seq": sequence_number,
                            "data": data,
                            "time": current_time,
                            "chs": checksum
                        }

                    # send ack of sequence number to sender immediately, so sender can keep sending more packets
                    self.send({ "type": "ack", "seq": sequence_number })
                    self.log(f"**Sending ack**; {sequence_number}")
                
                else:
                    # log received data message for corrupted packet & skip
                    self.log(f"**Received corrupted ack**; {sequence_number}")
                    continue
                    
                # sort the ack messages dict by sequence number, to order the packets, updates self.ack_messages
                self.sort_ack_messages()

                # iterate through the ack_messages dict, and print the packets in order
                self.print_ordered_packets()
                
                # delete the ack messages that have been printed, & clear the sequences_acknowledged list
                # so it doesnt get reprinted
                for sequences in self.sequences_acknowledged:
                    del self.ack_messages[sequences]
                self.sequences_acknowledged = []
        return


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='receive data')
    args = parser.parse_args()
    receiver = Receiver()
    receiver.run()
